services:
  app:
    build: .
    container_name: be-train-ocr
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
